version: '3.0'

networks:
  laravel:

#Web
services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports: 
      - "7000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel
  

  #Laravel 
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_laravel
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9004:9004"
    networks: 
      - laravel

#Composer  
  composer:
    image: composer:latest
    container_name: composer_laravel
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks: 
      - laravel
  

#npm
  npm: 
    image: node:13.7
    container_name: npm_laravel
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']


#artisan
  artisan:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: artisan_laravel
    volumes: 
      - ./src:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks: 
      - laravel

