version: '3.0'

networks:
  laravel:

#Web
services:

  nginx: 
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports: 
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  #Laravel 
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_laravel
    volumes: 
      - ./:/var/www/html
    ports: 
      - "9004:9004"
    networks: 
      - laravel
